name: "GitHub pages: deploy preview"

concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install R
        run: |
          curl --proto '=https' --tlsv1.3 -sSf https://raw.githubusercontent.com/eddelbuettel/r2u/6e130edb58db4d6328111e8eb2cc8583c1b07170/inst/scripts/add_cranapt_noble.sh | sudo bash
      - name: Install Python packages
        run: |
          pip install -r requirements.txt
      - name: Install R packages
        run: |
          sudo Rscript -e 'options(warn = 2); install.packages(c("tidyverse"))'
      - name: Install Javascript packages
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          umbrella-dir: preview
          source-dir: dist
          custom-url: trade-and-investment-factsheets.docs.trade.gov.uk
