name: "GitHub pages: tidy up preview"

concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          umbrella-dir: preview
          source-dir: dist
