name: "GitHub pages: deploy preview"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ubuntu packages
        run: sudo apt install libfontconfig1-dev libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python packages
        run: |
          pip install -r requirements.txt
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      - name: Fetch from / populate R package cache
        uses: actions/cache@v4
        with:
          # No need to hash the lockfile for the cache key, because this is itself a cache that the
          # below install step will pull a specific version of each package only if it needs to
          key: renv-packages
          path: |
            ~/.cache/R/renv
      - name: Install R packages
        run: |
          Rscript -e 'options(warn = 2); install.packages("renv", repos="https://cloud.r-project.org")'
          Rscript -e 'options(warn = 2); renv::restore()'
      - name: Install Javascript packages
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Deploy preview
        concurrency:
          group: preview-${{ github.event.number }}
        uses: rossjrw/pr-preview-action@v1
        with:
          umbrella-dir: preview
          source-dir: dist
          custom-url: trade-and-investment-factsheets.docs.trade.gov.uk
