name: "GitHub pages: deploy main"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "22 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt install r-base libfontconfig1-dev libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
          pip install -r requirements.txt
          sudo Rscript -e 'options(warn = 2); install.packages(c("tidyverse", "RCurl", "XML"), repos="https://cran.ma.imperial.ac.uk/")'
          npm ci
      - name: Build
        run: npm run build
      - name: Make sure to not run Jekyll
        run: touch dist/.nojekyll
      - name: Set CNAME
        run: echo "trade-and-investment-factsheets.docs.trade.gov.uk" >> dist/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          force: false
          clean-exclude: preview/
          folder: dist
          branch: gh-pages
