name: "Test packages"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ubuntu packages
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y gdebi-core devscripts
